### ISSUE TITLE
Roadmap to `V1`

### ISSUE THREAD

**Issue by Aditya-dom** [Aditya-dom/NFT-Wallet-ERC-6551-ERC-20#1]
This is the roadmap for getting TBA-ONCHAIN identity (ERC-6551) to a solid v1.

> High priority to-do list:

- [ ] Guardiens to recover 
- [ ] Multisig ike Safe wallet provides in Smart Wallet Accounts. Lets do it for TBA
- [ ] Swap, Buy, Sell of Tokens using Uniswap, 1 inch or Kyberswap..anything.
- [ ] Limit Orders, TP, SL for Traders
- [ ] Lending tokens using AAVE protocol at the moment.
- [ ] Cross chain Transfer using Lifi or CCTP by Circle.
- [ ] Multichain Compatibility so Quranium both layer can have same TBAs. LIke at themoment your NFT is in Sepolia, TBA should be compatible to all EVM.
- [ ] Yield Farming using third party protocol.
- [ ] Crypto etfs.
- [ ] Index fund buy sell
